# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - main
    - test

pr:
  branches:
    include:
    - master
    - test

parameters:
- name: environment
  displayName: 'Environment: test or prod'
  type: string
  default: none
  values:
    - none
    - test
    - prod

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- powershell: |
    Write-Host "Tagging Build: $env:BuildNumber"
    $currentCommit = git rev-parse HEAD # is this correct?

    git tag $env:BuildNumber
    git push origin $env:BuildNumber

    $currentDeployedTag = (Invoke-webrequest -URI "https://www.3shape.com/version.txt").Content
    $currentDeployedCommit = git show-ref -s $currentDeployedTag

    Write-Host "Currently deployed tag and commit:" $currentDeployedTag $currentDeployedCommit

    $username = 'JAndersen'
    $password = 'VG6NdUpB'

    $bytes = [System.Text.Encoding]::UTF8.GetBytes("$username`:$password")
    $encodedCredentials = [System.Convert]::ToBase64String($bytes)

    $commits = git log --pretty=oneline "$currentDeployedCommit...$currentCommit" --no-decorate --no-merges

    $commits | ForEach-Object {
        Write-Host $_
    }

    function Get-JiraIssue {    
      # We need authentication token
      param([string] $issueId)
      return Invoke-RestMethod -Uri "$jira_url/rest/api/latest/issue/$issueId" -Headers @{"Authorization" = "Basic $encodedCredentials" } -ContentType application/json 
    }

  env:
    BuildNumber: $(Build.BuildNumber)
- task: GitHubRelease@0
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: github.com_jimmilyhne
    repositoryName: '$(Build.Repository.Name)' #jimmilyhne/TestRepoRD
    action: 'create'
    tagSource: 'auto'
    tag: $(Build.BuildNumber)
    #title: # Optional
    releaseNotesSource: 'input' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    releaseNotes: 'This is the release notes generated from the Azure pipeline'
    # assets: |
    #   $(Build.ArtifactStagingDirectory)/*.exe
    #   $(Build.ArtifactStagingDirectory)/README.txt
