# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - main
    - test

pr:
  branches:
    include:
    - master
    - test

parameters:
- name: environment
  displayName: 'Environment: test or prod'
  type: string
  default: none
  values:
    - none
    - test
    - prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: git-tag-on-release-task@9
  displayName: "Add Tag to git"
  inputs:
    staticTagName: "TEST-$(Build.BuildNumber)"